quotes = [
    # Health
    "The greatest wealth is health. – Virgil",
    "Health is not just about what you're eating. It's also about what you're thinking and saying. – Unknown",
    "Take care of your body. It's the only place you have to live. – Jim Rohn",
    "Your health is an investment, not an expense. – Unknown",
    "The mind and body are not separate. What affects one, affects the other. – Unknown",
    "The first wealth is health. – Ralph Waldo Emerson",
    "A healthy outside starts from the inside. – Robert Urich",
    "Your body deserves the best. – Unknown",
    "Health is a state of complete harmony of the body, mind, and spirit. – B.K.S. Iyengar",
    "To enjoy the glow of good health, you must exercise. – Gene Tunney",
    
    # Scientists
    "Science is a way of thinking much more than it is a body of knowledge. – Carl Sagan",
    "The important thing is not to stop questioning. Curiosity has its own reason for existing. – Albert Einstein",
    "Science is the great antidote to the poison of enthusiasm and superstition. – Adam Smith",
    "Science is the best tool ever invented for understanding how the world works. – Unknown",
    "The science of today is the technology of tomorrow. – Edward Teller",
    "The beauty of science is that it can tell you what the universe is and how it works. – Neil deGrasse Tyson",
    "Science is not only compatible with spirituality; it is a profound source of spirituality. – Carl Sagan",
    "Science is a way of life that helps us make sense of the world. – Unknown",
    "The goal of science is to understand the universe and its contents. – Unknown",
    "The beauty of science is that it constantly evolves and adapts. – Unknown",
    
    # Libraries
    "A library is a hospital for the mind. – Anonymous",
    "Libraries are the backbone of democracy. – Unknown",
    "A library is a place where you can lose your mind and find your soul. – Anonymous",
    "The library is a place where you can find a world of possibilities. – Unknown",
    "Libraries are the quiet sanctuaries of learning and imagination. – Anonymous",
    "A library is a treasure chest of knowledge and wonder. – Unknown",
    "Libraries are the silent guardians of knowledge. – Anonymous",
    "In the library, every book is a new adventure. – Unknown",
    "A library is the most valuable resource of any community. – Anonymous",
    "Libraries are the keepers of our cultural heritage. – Unknown",
    
    # Books
    "A book is a gift you can open again and again. – Garrison Keillor",
    "Books are the mirrors of the soul. – Virginia Woolf",
    "Books are the perfect companions in solitude. – Anonymous",
    "A book is a device to ignite the imagination. – Alan Bennett",
    "Books are lighthouses erected in the great sea of time. – E.P. Whipple",
    "Books are a uniquely portable magic. – Stephen King",
    "The world was hers for the reading. – Betty Smith",
    "Books are the keys to wisdom’s treasure. – Anonymous",
    "Books are a form of therapy. – Anonymous",
    "Books are the ultimate companions. – Anonymous",
    
    # Motivation
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
    "The best way to predict your future is to create it. – Peter Drucker",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    
    # Health
    "A healthy mind in a healthy body is a very rich reward. – Anonymous",
    "Your health is a reflection of your lifestyle. – Unknown",
    "Good health is not something we can buy. However, it can be an extremely valuable savings account. – Anne Wilson Schaef",
    "Health is not valued until sickness comes. – Thomas Fuller",
    "The greatest wealth is health. – Virgil",
    "Take care of your body; it’s the only place you have to live. – Jim Rohn",
    "Health is the real wealth. – Mahatma Gandhi",
    "The best and most efficient pharmacy is within your own system. – Robert C. Peale",
    "Health is not just about what you're eating. It’s also about what you're thinking and saying. – Unknown",
    "The greatest wealth is health. – Virgil",
    
    # Scientists
    "The important thing is not to stop questioning. Curiosity has its own reason for existing. – Albert Einstein",
    "Science is the great antidote to the poison of enthusiasm and superstition. – Adam Smith",
    "Science is a way of thinking much more than it is a body of knowledge. – Carl Sagan",
    "The goal of science is to understand the universe and its contents. – Unknown",
    "Science is not only compatible with spirituality; it is a profound source of spirituality. – Carl Sagan",
    "Science is a way of life that helps us make sense of the world. – Unknown",
    "The beauty of science is that it can tell you what the universe is and how it works. – Neil deGrasse Tyson",
    "Science is a tool for understanding the world, not a source of final answers. – Unknown",
    "Science is the best tool ever invented for understanding how the world works. – Unknown",
    "The beauty of science is that it constantly evolves and adapts. – Unknown",
    
    # Libraries
    "A library is a hospital for the mind. – Anonymous",
    "Libraries are the backbone of democracy. – Unknown",
    "A library is a place where you can lose your mind and find your soul. – Anonymous",
    "Libraries are the silent guardians of knowledge. – Anonymous",
    "In the library, every book is a new adventure. – Unknown",
    "A library is a treasure chest of knowledge and wonder. – Unknown",
    "Libraries are the keepers of our cultural heritage. – Unknown",
    "A library is a place where you can find a world of possibilities. – Anonymous",
    "Libraries are the quiet sanctuaries of learning and imagination. – Anonymous",
    "A library is the most valuable resource of any community. – Anonymous",
    
    # Books
    "A book is a gift you can open again and again. – Garrison Keillor",
    "Books are the mirrors of the soul. – Virginia Woolf",
    "Books are the perfect companions in solitude. – Anonymous",
    "A book is a device to ignite the imagination. – Alan Bennett",
    "Books are lighthouses erected in the great sea of time. – E.P. Whipple",
    "Books are a uniquely portable magic. – Stephen King",
    "The world was hers for the reading. – Betty Smith",
    "Books are the keys to wisdom’s treasure. – Anonymous",
    "Books are a form of therapy. – Anonymous",
    "Books are the ultimate companions. – Anonymous",
    
    # Motivation
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
    "The best way to predict your future is to create it. – Peter Drucker",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    
    # Health
    "A healthy mind in a healthy body is a very rich reward. – Anonymous",
    "Your health is a reflection of your lifestyle. – Unknown",
    "Good health is not something we can buy. However, it can be an extremely valuable savings account. – Anne Wilson Schaef",
    "Health is not valued until sickness comes. – Thomas Fuller",
    "The greatest wealth is health. – Virgil",
    "Take care of your body; it’s the only place you have to live. – Jim Rohn",
    "Health is the real wealth. – Mahatma Gandhi",
    "The best and most efficient pharmacy is within your own system. – Robert C. Peale",
    "Health is not just about what you're eating. It’s also about what you're thinking and saying. – Unknown",
    "The greatest wealth is health. – Virgil",
    
    # Scientists
    "The important thing is not to stop questioning. Curiosity has its own reason for existing. – Albert Einstein",
    "Science is the great antidote to the poison of enthusiasm and superstition. – Adam Smith",
    "Science is a way of thinking much more than it is a body of knowledge. – Carl Sagan",
    "The goal of science is to understand the universe and its contents. – Unknown",
    "Science is not only compatible with spirituality; it is a profound source of spirituality. – Carl Sagan",
    "Science is a way of life that helps us make sense of the world. – Unknown",
    "The beauty of science is that it can tell you what the universe is and how it works. – Neil deGrasse Tyson",
    "Science is a tool for understanding the world, not a source of final answers. – Unknown",
    "Science is the best tool ever invented for understanding how the world works. – Unknown",
    "The beauty of science is that it constantly evolves and adapts. – Unknown",
    
    # Libraries
    "A library is a hospital for the mind. – Anonymous",
    "Libraries are the backbone of democracy. – Unknown",
    "A library is a place where you can lose your mind and find your soul. – Anonymous",
    "Libraries are the silent guardians of knowledge. – Anonymous",
    "In the library, every book is a new adventure. – Unknown",
    "A library is a treasure chest of knowledge and wonder. – Unknown",
    "Libraries are the keepers of our cultural heritage. – Unknown",
    "A library is a place where you can find a world of possibilities. – Anonymous",
    "Libraries are the quiet sanctuaries of learning and imagination. – Anonymous",
    "A library is the most valuable resource of any community. – Anonymous",
    
    # Books
    "A book is a gift you can open again and again. – Garrison Keillor",
    "Books are the mirrors of the soul. – Virginia Woolf",
    "Books are the perfect companions in solitude. – Anonymous",
    "A book is a device to ignite the imagination. – Alan Bennett",
    "Books are lighthouses erected in the great sea of time. – E.P. Whipple",
    "Books are a uniquely portable magic. – Stephen King",
    "The world was hers for the reading. – Betty Smith",
    "Books are the keys to wisdom’s treasure. – Anonymous",
    "Books are a form of therapy. – Anonymous",
    "Books are the ultimate companions. – Anonymous",
    
    # Motivation
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
    "The best way to predict your future is to create it. – Peter Drucker",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    
    # Health
    "A healthy mind in a healthy body is a very rich reward. – Anonymous",
    "Your health is a reflection of your lifestyle. – Unknown",
    "Good health is not something we can buy. However, it can be an extremely valuable savings account. – Anne Wilson Schaef",
    "Health is not valued until sickness comes. – Thomas Fuller",
    "The greatest wealth is health. – Virgil",
    "Take care of your body; it’s the only place you have to live. – Jim Rohn",
    "Health is the real wealth. – Mahatma Gandhi",
    "The best and most efficient pharmacy is within your own system. – Robert C. Peale",
    "Health is not just about what you're eating. It’s also about what you're thinking and saying. – Unknown",
    "The greatest wealth is health. – Virgil",
    
    # Scientists
    "The important thing is not to stop questioning. Curiosity has its own reason for existing. – Albert Einstein",
    "Science is the great antidote to the poison of enthusiasm and superstition. – Adam Smith",
    "Science is a way of thinking much more than it is a body of knowledge. – Carl Sagan",
    "The goal of science is to understand the universe and its contents. – Unknown",
    "Science is not only compatible with spirituality; it is a profound source of spirituality. – Carl Sagan",
    "Science is a way of life that helps us make sense of the world. – Unknown",
    "The beauty of science is that it can tell you what the universe is and how it works. – Neil deGrasse Tyson",
    "Science is a tool for understanding the world, not a source of final answers. – Unknown",
    "Science is the best tool ever invented for understanding how the world works. – Unknown",
    "The beauty of science is that it constantly evolves and adapts. – Unknown",
    
    # Libraries
    "A library is a hospital for the mind. – Anonymous",
    "Libraries are the backbone of democracy. – Unknown",
    "A library is a place where you can lose your mind and find your soul. – Anonymous",
    "Libraries are the silent guardians of knowledge. – Anonymous",
    "In the library, every book is a new adventure. – Unknown",
    "A library is a treasure chest of knowledge and wonder. – Unknown",
    "Libraries are the keepers of our cultural heritage. – Unknown",
    "A library is a place where you can find a world of possibilities. – Anonymous",
    "Libraries are the quiet sanctuaries of learning and imagination. – Anonymous",
    "A library is the most valuable resource of any community. – Anonymous",
    
    # Books
    "A book is a gift you can open again and again. – Garrison Keillor",
    "Books are the mirrors of the soul. – Virginia Woolf",
    "Books are the perfect companions in solitude. – Anonymous",
    "A book is a device to ignite the imagination. – Alan Bennett",
    "Books are lighthouses erected in the great sea of time. – E.P. Whipple",
    "Books are a uniquely portable magic. – Stephen King",
    "The world was hers for the reading. – Betty Smith",
    "Books are the keys to wisdom’s treasure. – Anonymous",
    "Books are a form of therapy. – Anonymous",
    "Books are the ultimate companions. – Anonymous",
    
    # Motivation
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
    "The best way to predict your future is to create it. – Peter Drucker",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    
    # Health
    "A healthy mind in a healthy body is a very rich reward. – Anonymous",
    "Your health is a reflection of your lifestyle. – Unknown",
    "Good health is not something we can buy. However, it can be an extremely valuable savings account. – Anne Wilson Schaef",
    "Health is not valued until sickness comes. – Thomas Fuller",
    "The greatest wealth is health. – Virgil",
    "Take care of your body; it’s the only place you have to live. – Jim Rohn",
    "Health is the real wealth. – Mahatma Gandhi",
    "The best and most efficient pharmacy is within your own system. – Robert C. Peale",
    "Health is not just about what you're eating. It’s also about what you're thinking and saying. – Unknown",
    "The greatest wealth is health. – Virgil",
    
    # Scientists
    "The important thing is not to stop questioning. Curiosity has its own reason for existing. – Albert Einstein",
    "Science is the great antidote to the poison of enthusiasm and superstition. – Adam Smith",
    "Science is a way of thinking much more than it is a body of knowledge. – Carl Sagan",
    "The goal of science is to understand the universe and its contents. – Unknown",
    "Science is not only compatible with spirituality; it is a profound source of spirituality. – Carl Sagan",
    "Science is a way of life that helps us make sense of the world. – Unknown",
    "The beauty of science is that it can tell you what the universe is and how it works. – Neil deGrasse Tyson",
    "Science is a tool for understanding the world, not a source of final answers. – Unknown",
    "Science is the best tool ever invented for understanding how the world works. – Unknown",
    "The beauty of science is that it constantly evolves and adapts. – Unknown",
    
    # Libraries
    "A library is a hospital for the mind. – Anonymous",
    "Libraries are the backbone of democracy. – Unknown",
    "A library is a place where you can lose your mind and find your soul. – Anonymous",
    "Libraries are the silent guardians of knowledge. – Anonymous",
    "In the library, every book is a new adventure. – Unknown",
    "A library is a treasure chest of knowledge and wonder. – Unknown",
    "Libraries are the keepers of our cultural heritage. – Unknown",
    "A library is a place where you can find a world of possibilities. – Anonymous",
    "Libraries are the quiet sanctuaries of learning and imagination. – Anonymous",
    "A library is the most valuable resource of any community. – Anonymous",
    
    # Books
    "A book is a gift you can open again and again. – Garrison Keillor",
    "Books are the mirrors of the soul. – Virginia Woolf",
    "Books are the perfect companions in solitude. – Anonymous",
    "A book is a device to ignite the imagination. – Alan Bennett",
    "Books are lighthouses erected in the great sea of time. – E.P. Whipple",
    "Books are a uniquely portable magic. – Stephen King",
    "The world was hers for the reading. – Betty Smith",
    "Books are the keys to wisdom’s treasure. – Anonymous",
    "Books are a form of therapy. – Anonymous",
    "Books are the ultimate companions. – Anonymous",
    
    # Motivation
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
    "The best way to predict your future is to create it. – Peter Drucker",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill"
]
