# Generated by Django 5.0.4 on 2024-08-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.URLField(default=None, null=True, verbose_name='Photo Url'),
        ),
    ]
