# Generated by Django 5.0.4 on 2024-08-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_author_books_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='categories',
        ),
        migrations.AddField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(to='books.category', verbose_name='categories'),
        ),
    ]
