# Generated by Django 5.0.4 on 2024-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreport',
            name='have_now',
            field=models.BooleanField(default=False),
        ),
    ]
