# Generated by Django 5.0.4 on 2024-08-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transactionreport_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionreport',
            old_name='returned',
            new_name='read',
        ),
    ]
