# Generated by Django 5.0.4 on 2024-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_rename_returned_transactionreport_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreport',
            name='balance_then',
            field=models.IntegerField(default=0),
        ),
    ]
