# Generated by Django 5.0.4 on 2024-08-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_user'),
        ('books', '0003_remove_books_categories_books_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='borrowed_by', to='books.books'),
        ),
    ]
